name: devleomobile
description: A project to demonstrate various applications developed in Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_share: ^2.0.0
  http: ^0.13.6
  path_provider: ^2.0.15
  share: ^2.0.4
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imgs/fundo.jpg
    - imgs/camisaVasco.jpg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
